{
 "title": "Fiapx Worker Monitoring",
 "tags": [ "worker" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Video Processing Rate (per status)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(worker_videos_processed_total[5m]) by (status)",
     "legendFormat": "Video Status: {{status}}"
    }
   ]
  },
  {
   "title": "Average Video Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(worker_video_processing_duration_seconds_sum[5m])) / sum(rate(worker_video_processing_duration_seconds_count[5m]))",
     "legendFormat": "Avg Processing Time"
    }
   ]
  },
  {
   "title": "Worker Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"fiapx-worker\"}",
     "legendFormat": "Allocated Memory"
    }
   ]
  },
  {
   "title": "Worker Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"fiapx-worker\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Worker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fiapx-worker\"}[5m])",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}